import type { Metadata } from "next";
import {
  Bona_Nova,
  Joan,
  Poppins,
  Roboto_Slab,
  WindSong
} from "next/font/google";
import "./globals.css";

const roboto = Roboto_Slab({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Adjuster-Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
